modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="craftersarmor"
version="1.0.0"
displayName="Crafters Armor"
authors="Crafters CR"
description='''
Agrega armaduras y cosméticos personalizados de Crafters CR.
'''

[[dependencies.craftersarmor]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.craftersarmor]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.craftersarmor]]
modId="geckolib"
type="required"
versionRange="[4.9,5)"
ordering="AFTER"
side="BOTH"